### ISSUE TITLE
protoc-gen-go: Can't  build protobuf  on windows 10   golang go1.15 windows/amd64  libprotoc 3.12.3

### ISSUE THREAD

**Issue by wakaaa1234** [golang/protobuf#1327]
**What version of protobuf and what language are you using?**
F:\gocode\server\user>go version
go version go1.15 windows/amd64

**What did you do?**
If possible, provide a recipe for reproducing the error.
A complete runnable program is good with `.proto` and `.go` source code.

I try to build protobuf file to get a  golang code, but It is failed.

following is what I do.

1. check windows version

Microsoft Windows [版本 10.0.18363.900]
(c) 2019 Microsoft Corporation。

2. check  golang version and protoc version

 F:\gocode\server\user>go version
go version go1.15 windows/amd64

F:\gocode\server\user>protoc --version
libprotoc 3.12.3

3. check  protoc-gen-go version is ready
F:\gocode\server>protoc-gen-go version
protoc-gen-go: unknown argument "version" (this program should be run by protoc, not directly). 
This make sure protoc-gen-go is ready.
[
 I use this command to install  protoc-gen-go
go get google.golang.org/protobuf/cmd/protoc-gen-go
go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
]

5. check helloworld.proto file is correct

F:\gocode\server\user>copy helloworld.proto con
syntax = "proto3";

option go_package = "demo.rpc.com/helloworld";
option java_multiple_files = true;
option java_package = "io.grpc.examples.helloworld";
option java_outer_classname = "HelloWorldProto";

package helloworld;

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
}

6. run the build command 

F:\gocode\server\user>protoc --go_out=plugins=grpc:. helloworld.proto
ERROR: 2021/06/03 10:27:15 [profiling] error parsing flags: when -address isn't specified, you must include -stream-stats-catapult-json
--go_out: protoc-gen-go: Plugin failed with status code 1.

I don't know how to fix this issue? 

 Also I try to run another command which is from ( https://grpc.io/docs/languages/go/quickstart/)

F:\gocode\server\user>protoc --go_out=. --go_opt=paths=source_relative   --go-grpc_out=. --go-grpc_opt=paths=source_relative  helloworld.proto
ERROR: 2021/06/03 10:26:11 [profiling] error parsing flags: when -address isn't specified, you must include -stream-stats-catapult-json
--go_out: protoc-gen-go: Plugin failed with status code 1.

So anyone can tell me how to do? or tell me how to dig this issue. Thanks.
 

**What did you expect to see?**

**What did you see instead?**

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment?**

**Comment by neild** [comment]
So far as I can tell, the error "when -address isn't specified, you must include -stream-stats-catapult-json" comes from here:
https://github.com/grpc/grpc-go/blob/master/profiling/cmd/flags.go#L60

I do not understand how that code can possibly be invoked by the commands that you list. It's not part of any of the protobuf code generation, either for the base messages (`protoc-gen-go`) or for gRPC services (`protoc-gen-go-grpc`).

**Comment by wakaaa1234** [comment]
When I upgrade libprotoc from 3.12.3 to 3.17.2 , and re-install the  protoc-gen-go, and protoc-gen-go-grpc package. I found all things  go well.   :) . So It is resolved.

C:\Users\xx>protoc --version
libprotoc 3.17.2

**Comment by 3r1co** [comment]
Hello, could we please reopen this issue? I'm facing the same problem, but upgrade to the latest protoc version doesn't help (I tried with 3.17.3 and 3.17.2). Thank you!

**Comment by neild** [comment]
I still don't understand how that error can be produced by `protoc`, `protoc-gen-go` and/or `protoc-gen-go-grpc`, given that the only place it seems to be defined is a completely different binary. It will probably need some extremely specific reproduction steps, including exactly where every binary invoked was acquired from, to offer any useful advice. (It looks almost as if the `protoc-gen-go-grpc` binary was replaced with a completely different program? You could try reinstalling `protoc-gen-go-grpc` from a known-good source to start with.)

In addition, this error seems to come from a gRPC-related source; you'll have better luck asking the Go gRPC maintainers: https://github.com/grpc/grpc-go/issues
